# Generated by Django 2.1.4 on 2018-12-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel',
            name='cancel_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cancel',
            name='supplementary_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
