# Generated by Django 2.1.4 on 2018-12-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20181220_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancel',
            old_name='send_tomorrow_flag',
            new_name='send_cancel_tomorrow_flag',
        ),
        migrations.RenameField(
            model_name='cancel',
            old_name='send_week_flag',
            new_name='send_cancel_week_flag',
        ),
        migrations.AddField(
            model_name='cancel',
            name='send_sup_tomorrow_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancel',
            name='send_sup_week_flag',
            field=models.BooleanField(default=False),
        ),
    ]
